### ISSUE TITLE
Session Flash

### ISSUE THREAD

**Issue by hendrasyp** [Shifrin/yii2-noty#5] opened 2016-02-18 07:22 UTC
Thanks for this useful widget.

How to disable flash on `enableSessionFlash` ? . If I set to `false` , return me error `undefine variable $view` .

so I make changes in NotyWidget.php : 

```
public function run()
{
  $this->registerAssets();
  $this->registerPlugin();
  $view = $this->getView();
  $script = "";
  if ($this->enableSessionFlash) 
  {
    $flashes = Yii::$app->session->getAllFlashes();
    foreach($flashes as $type => $message) 
    {
      if (empty($message))
      {
          continue;
      }
      $type = $this->verifyType($type);
      $icon = $this->getIcon($type);
      $text = is_array($message) ? $icon . implode(' ', $message) : $icon . $message;
      $script .= "var {$type} = Noty('{$this->getId()}');\r\n";
      $script .= "$.noty.setText({$type}.options.id, '{$text}');\r\n";
      $script .= "$.noty.setType({$type}.options.id, '{$type}');\r\n";
    }
  }else{
      $view = $this->getView();
  }
  $view->registerJs($script);
}
```

**Comment by Shifrin** [comment] 2016-02-21 07:03
Thank you for using my widget and suggestion. The problem is fixed now. Please check here https://github.com/Shifrin/yii2-noty/commit/a818379e79a7ea218b58cb4efc01cc2f45f40d4f.

**Comment by Shifrin** [comment] 2016-02-21 07:03
Thank you for using my widget and suggestion. The problem is fixed now. Please check here a818379.

**Closed as completed by Shifrin** 2016-02-21 07:03 UTC
Labels: bug
